### ISSUE TITLE
The 'set manual location' view on the observation create/edit view needs love

### ISSUE THREAD

**Issue by lemmingapex** [ngageoint/mage-android#20]
Below is a list of smaller issues I've seen on this screen:
- Add a margin to the latitude and longitude controls to match parent screen.
- The precision of the latitude and longitude are much too high in these boxes.  Consider only using 5 decimal points.
- The soft keyboard allows all alpha-numeric input.  Should restrict input to 0123456789.- and change the soft keyboard type.  Why can I put a return character in these fields?
- The listeners need some work.  Keyup or keyboard hide should probably set the lat/lon.  Currently, some changes may not be saved.  Play around with the focus of the keyboard, and you'll see what I mean.

The above fixes should resolve some other artifacts I've seen on this screen as well.

**Comment by newmanw** [comment]
Some of this has been fixed as part of material design update here:
