### ISSUE TITLE
No target assembleLocalDebug

### ISSUE THREAD

**Issue by bradh** [ngageoint/mage-android#33]
https://github.com/ngageoint/mage-android/blob/master/README.md#build says that 
`./gradlew assembleLocalDebug`
should be used.

That isn't working for me. With a command line build, I get 
```
$ ./gradlew assembleLocalDebug
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/bradh/Android/Sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.


FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleLocalDebug' not found in root project 'mage-android'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.123 secs
```

From the tasks list, I tried "assembleDebug" instead, but that failed with some resources problems:
```
:mage:processDefaultsDebugResources
/home/bradh/StudioProjects/mage-android/mage/src/main/res/xml/aboutpreferences.xml:6:22-42: AAPT: No resource found that matches the given name (at 'key' with value '@string/serverURLKey').
```

I'm trying to build on a Linux 1710 VM, javac 1.8.0_171, using the provided gradle wrapper.

**Comment by newmanw** [comment]
@bradh I updated the instructions here: https://github.com/ngageoint/mage-android/#build

Also make sure you grab the MAGE SDK, build and deploy to your local maven repo.  Instructions here: https://github.com/ngageoint/mage-android-sdk#how-to-build.
