### ISSUE TITLE
Set Url Activity

### ISSUE THREAD

**Issue by Jufi-101** [ngageoint/mage-android#37]
This looks like its a beautiful app, but after going through the ordeal of setting it up. I came across the Activity thats asking for a server URL. so whats the server url

**Comment by newmanw** [comment]
There is no central server, you will need to setup and manage your own server.

https://github.com/ngageoint/mage-server/blob/master/README.md

**Comment by Jufi-101** [comment]
i setup the server, but when i try setting the url, it produces an error "Connection closed by peer"

**Comment by newmanw** [comment]
Are you running over http?  If so you will need to modify the http client manager to allow for http connections. Not recommended for anything other than debug.

**Comment by Jufi-101** [comment]
i changed the https request to http, which worked but now the app displays an alert dialog "App Compatibility error", "This app is not compatible with this server. Please update your context or talk to your MAGE administrator."

**Comment by restjohn** [comment]
What sort of feedback does the app give you when you attempt to login your new user?

**Comment by Jufi-101** [comment]
it says, app compatibility error

**Comment by restjohn** [comment]
Have you set a break point in [ServerApi.isValid()](https://github.com/ngageoint/mage-android-sdk/blob/fb15653a17fcf74c2237b67a44ba11391fcc9bd7/sdk/src/main/java/mil/nga/giat/mage/sdk/preferences/ServerApi.java#L76) to see whether that check passes?  If not, you may need to make sure you are using compatible versions of the app and server and that your server is appropriately [configured](https://github.com/ngageoint/mage-server/blob/master/README.md#configuring-and-customizing-mage).

**Comment by Jufi-101** [comment]
Yes,i have and it does not pass. i figured since am configuring from the latest commits, both server, app and sdk. they would be compatible.

**Comment by restjohn** [comment]
You could try setting up your server from the [5.2.6 release](https://github.com/ngageoint/mage-server/releases/tag/5.2.6) tag and using the app version from the Google Play Store.  Are you building and running the server, SDK, and app from their respective master branches or from release tags?  What are the debug values you see when you breakpoint in the `Server.isValid()` check that is causing it to fail?
