### ISSUE TITLE
Adding audio file to observation

### ISSUE THREAD

**Issue by fm-davidcraig** [ngageoint/mage-android#40]
I'm a new user but have seen two issues in the Android build from google play 6.4
First one is that the app crashes if event does not have form. This appears to be fixed in 6.5 will 6.5 be uploaded to the play store?

My other bug is that everything works fine but when adding an audio recording to the observation when I press done it closes out of both the audio recorder and the observation window and save neither. I'm using a Samsung S8 Active with Android Pie.

We have other Samsung S8 in our fleet so I will try them tomorrow. The video and other attachment work fine. Thanks for all you do!

**Comment by newmanw** [comment]
6.2.5 shows as available on the Play Store on August 2nd.  Are you not able to see that update from your device?

Since there is no default audio recorder on Android I need a little more info.  What audio recording app are you using?

**Comment by fm-davidcraig** [comment]
Great I have updated Mage app from store. The voice recorder appears to come with Samsung and is called voice recorder. I'm using version 21.

I could try un-installing and try a different one I was unsure of if the record audio used the default rwcorder.

Thanks
________________________________

**Comment by fm-davidcraig** [comment]
[Image]

**Comment by fm-davidcraig** [comment]
I tried uninstalling and using a different one only issue is Mage does not see it has a defualt voice recorder and I don't see anything in pie that lets me set that.

Thanks

________________________________

**Comment by newmanw** [comment]
Awesome, thanks for the info.  I was able to reproduce what you are seeing, should have a fix shortly.
